logging:
    file:
        name: logs/ch09.log
    level:
        root: info
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
server:
    port: 8080
    servlet:
        context-path: /ch09
spring:
    servlet:
      multipart:
        max-file-size: 10MB
    application:
        name: ch09
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        password: 1234
        url: jdbc:oracle:thin:@//localhost:1521/xe
        username: os3754
    devtools:
        livereload:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true

jwt:
  issuer: yd89023754@gmail.com
  secret: E912C15AA2495217ECD6BE5BEA8D1102

file:
  upload:
    path: uploads

